name: Phantom
on:
  workflow_dispatch:
  schedule:
    - cron: '57 5,10,11 * * *'
jobs:
  mission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install cryptography playwright --quiet
      - run: python awaken.py
        env:
          ENC_KEY: ${{ secrets.ENC_KEY }}
          PAYLOAD_BIN: ${{ secrets.PAYLOAD_BIN }}
